kind: pipeline
name: Build

steps:
- name: build
  image: devilbox/php-fpm:7.2-work
  environment:
    FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:crm:80'
    PHP_MODULES_DISABLE: xdebug
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - chmod +x ./travis-ci/*.sh
  - chmod +x ./scripts/*.sh
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen

- name: restore-cache
  image: drillster/drone-volume-cache
  restore: true
  mount:
    - ./scripts
    - ./tests
    - ./src
  # Mount the cache volume, needs "Trusted"
  volumes:
  - name: cache
    path: /cache
  cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_JOB_NUMBER ]

- name: Test-7.2
  image: devilbox/php-fpm:7.2-work
  environment:
    FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:crm:80'
    PHP_MODULES_DISABLE: xdebug
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - mysql --user=root --password=churchcrm --host=mysql -e "drop database IF EXISTS churchcrm_test;"
  - mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test

- name: retest-cache
  image: drillster/drone-volume-cache
  rebuild: true
  mount:
    - ./scripts
    - ./tests
    - ./src
  # Mount the cache volume, needs "Trusted"
  volumes:
  - name: cache
    path: /cache
  cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_JOB_NUMBER ]

- name: test
  image: alpine
  commands:
    - cat ./tests/behat/behat.yml

services:
- name: php
  image: devilbox/php-fpm:7.2-work
  detach: true
  environment:
    FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:crm:80'
    PHP_MODULES_DISABLE: xdebug
  commands:
    - mkdir /var/www/default
    - ln -s /drone/src/src/ /var/www/default/htdocs
    - /docker-entrypoint.sh
  working_dir: /var/www/default

- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: 'churchcrm'

- name: crm
  image: devilbox/apache-2.4
  environment:
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php
    PHP_FPM_SERVER_PORT: 9000
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm
  commands:
    - rm -rf /var/www/default/htdocs
    - ln -s /drone/src/src/ /var/www/default/htdocs
    - /docker-entrypoint.sh
  working_dir: /var/www/default

- name: selenium
  image: selenium/standalone-chrome
  volumes:
    - name: shm
      path: /dev/shm:/dev/shm

volumes:
- name: cache
  path: /tmp/cache