kind: pipeline
name: default

steps:
- name: frontend
  image: devilbox/php-fpm:7.2-work
  environment:
    FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:crm:80'
    PHP_MODULES_DISABLE: xdebug
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - chmod +x ./travis-ci/*.sh
  - chmod +x ./scripts/*.sh
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen
  - sed -i "s;/vagrant;/drone/src;g" ./scripts/tests-run.sh
  - sed -i 's;{"goutte"\ :\ "~","selenium2":"~"};{"selenium2"\ :\ {\ "wd_host":\ "http://selenium:4444/wd/hub"}};g' ./scripts/tests-run.sh
  - sed -i "s/SERVERNAME = 'localhost';/SERVERNAME = 'mysql';/g" ./tests/bootstrap.php
  - sed -i "s,$sRootPath = '/src';,$sRootPath = '';,g" ./tests/bootstrap.php
  - npm run tests-install
  - mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - cp ./travis-ci/Config.php ./src/Include/Config.php
  - sed -i "s/SERVERNAME = 'localhost';/SERVERNAME = 'mysql';/g" ./src/Include/Config.php
  - sed -i "s/PASSWORD = '';/PASSWORD = 'churchcrm';/g" ./src/Include/Config.php
  - sed -i "s;'http://127.0.0.1/';'http://crm/';g" ./src/Include/Config.php
  - sed -i "s;http://localhost;http://crm;g" ./tests/behat/behat.yml
  - sed -i "s;Chrome;chrome;g" ./tests/behat/behat.yml
  - sed -i "s;platform:\ Windows\ 10;browser:\ chrome;g" ./tests/behat/behat.yml
  - sed -i "s;version:\ 67.0;marionette:\ true;g" ./tests/behat/behat.yml
  - cat ./scripts/tests-run.sh
  - cat ./tests/bootstrap.php
  - cat ./src/Include/Config.php
  - cat ./tests/behat/behat.yml
  - npm run test

services:
- name: php
  image: devilbox/php-fpm:7.2-work
  environment:
    FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:crm:80'
    PHP_MODULES_DISABLE: xdebug
  commands:
    - mkdir /var/www/default
    - ln -s /drone/src/src/ /var/www/default/htdocs
    - /docker-entrypoint.sh
  working_dir: /var/www/default

- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: 'churchcrm'

- name: crm
  image: devilbox/apache-2.4
  environment:
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php
    PHP_FPM_SERVER_PORT: 9000
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm
  commands:
    - rm -rf /var/www/default/htdocs
    - ln -s /drone/src/src/ /var/www/default/htdocs
    - /docker-entrypoint.sh
  working_dir: /var/www/default

- name: selenium
  image: selenium/standalone-chrome
  volumes:
    - name: shm
      path: /dev/shm:/dev/shm
